# Generated by Django 4.2.5 on 2024-04-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_alter_matchhistory_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='ai',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='loser_id2',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='loser_id3',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='winner_id2',
        ),
    ]
