# Generated by Django 4.2.5 on 2024-04-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
