# Generated by Django 4.2.5 on 2024-04-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_alter_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='elo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='message',
        ),
    ]
