# Generated by Django 4.2.5 on 2024-04-09 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_remove_usuario_elo_remove_usuario_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator('Email invalid. Enter a valid email address')]),
        ),
    ]
