# Generated by Django 4.2.5 on 2024-06-07 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Enter a valid password. It must be at least 8 characters long, include at least one uppercase letter, one number and one special character.', regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[._!"`\\\'#$%&,:;<>=@{}~\\$\\(\\)\\*\\+\\/\\\\\\?\\[\\]\\^\\|])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
    ]
