# Generated by Django 4.2.5 on 2024-06-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0011_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='language',
            field=models.CharField(default='en', max_length=3),
        ),
    ]
