# Generated by Django 4.2.5 on 2024-07-17 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0012_usuario_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='winner_id1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_id1', to=settings.AUTH_USER_MODEL),
        ),
    ]
